api_platform:
    title: Sales Tracker API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld:  ['application/ld+json']
        json:    ['application/json']
        jsonapi: ['application/vnd.api+json']
        xml:     ['application/xml', 'text/xml']
        yaml:    ['application/x-yaml']
        csv:     ['text/csv']
        html:    ['text/html']
    patch_formats:
        jsonld:  ['application/ld+json']
        json: ['application/json']
    error_formats:
        jsonproblem: ['application/problem+json']
        jsonld: ['application/ld+json']      # Hydra error formats
        jsonapi: ['application/vnd.api+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
    eager_loading:
        force_eager: true
