#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# login | request token route
authentication:
  path: /auth
  methods: ['POST']

get_current_user:
  path: /current-user
  controller: App\Controller\SecurityController::user
  methods: ['GET']

get_roles:
  path: /get-roles
  controller: App\Controller\GetRolesController
  methods: ['GET']
